FROM nginx:latest

# HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
# CMD curl --fail http://localhost:8001 || exit 1

CMD /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && envsubst < /etc/nginx/conf.d/vhosts.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"